# Generated by Django 5.0.6 on 2024-06-26 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name': 'Ютуб', 'verbose_name_plural': 'Ютуб'},
        ),
        migrations.AddField(
            model_name='youtube',
            name='slogan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sport.slogan', verbose_name='Слоган'),
            preserve_default=False,
        ),
    ]
